inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/migrate/**
    - db/schema.rb
    - vendor/bundle/**/*

Rails:
  Enabled: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 180
  IgnoredPatterns:
    - '\A\s*#' # allow long comments

# Offense count: 166
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 25
  ExcludedMethods:
    - 'configure_blacklight'
    - 'Dor.configure'
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'lib/tasks/*.rake'
