
# Example settings for configuration
# NOTE:  Please use lowercase.
#   The config gem documents the correct usage as lowercase: https://github.com/railsconfig/config#embedded-ruby-erb
#   If we use uppercase the config gem ends up creating methods with the ruby convention for constants, which is confusing.

# General
date_format_str: '%Y-%m-%d %H:%M:%S.%L'

# Bulk Metadata
bulk_metadata:
  directory: '/tmp/bulk_jobs/'
  temporary_directory: '/tmp/bulk_jobs/tmp/'
  log: 'log.txt'
  csv_log: 'log.csv'
  xml: 'MODS'
  zip: 'desc_metadata_download.zip'

checksum_report_job:
  csv_filename: 'checksum_report.csv'

# Newrelic
newrelic:
  enabled: false
  license_key: 'super secret api key'
  app_name: 'Argo - name should be specific to server'

# Profiler
profiler:
  ##
  # A bit different but for RackMiniProfiler https://github.com/MiniProfiler/rack-mini-profiler
  # useful for profiling blocking HTTP requests and partial rendering
  rackmini_enabled: false

# # SSL
# ssl:
#   cert_file: 'cert_name.crt'
#   key_file: 'key_name.key'
#   key_pass: 'password'

# Stacks
stacks:
  local_workspace_root: '/foo/workspace'

# Suri
suri:
  mint_ids: true
  id_namespace: 'druid'
  url: 'http://localhost:3002'
  user: 'user'
  pass: 'pass'

dor_services:
  url: 'http://localhost:3003'
  # To generate the token: docker-compose run dor-services-app rake generate_token
  token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGb28ifQ.-BVfLTW9Q1_ZQEsGv4tuzGLs5rESN7LgdtEwUltnKv4

preservation_catalog:
  url: 'https://example.org/prescat'

# URLs
dor_indexing_url: 'https://dor-indexing-app.example.com/dor'
fedora_url: 'https://user:password@fedora.example.com:1000/fedora'
modsulator_url: 'https://services.example.com/v1/modsulator'
normalizer_url: 'https://services.example.com/v1/normalizer'
purl_url: 'https://purl.example.com'
robot_status_url: 'https://robot.example.com/robots'
solrizer_url: 'https://solr.example.com/solr/collection'
spreadsheet_url: 'https://services.example.com/v1/spreadsheet'
stacks_file_url: 'https://stacks.example.com/file'
stacks_url: 'https://stacks.example.com/image'
status_indexer_url: 'https://status.example.com/render/?format=json&other=params'
workflow_url: 'http://localhost:3001'

# Workflow
workflow:
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'

apo:
  default_workflow_option: 'registrationWF'

# These workflows are inactive, and the workflow-server doesn't know about them
# so we don't draw them on the workflow grid
inactive_workflows:
  - accession2WF
  - sdrMigrationWF
  - dpgImageWF
  - sdrAuditWF
  - swIndexWF
  - googleScannedBookWF
  - eemsAccessionWF
